### ISSUE TITLE
How can I use my noisy gps data to map_matching on my OSM map?

### ISSUE THREAD

**Issue by mrmrn** [categulario/map_matching#16]
Dear Abraham,
I have a database of noisy data from some devices and a history of this devices.
I want to map matching this data at first, then estimate a real time traffic.
can I use your code for starting my  project?

**Comment by categulario** [comment]
Yes you can! Although there may be better options in terms of speed. I'm in the process of rewrite this to the rust programming language.

Please check out https://github.com/Project-OSRM/osrm-backend/ and https://github.com/valhalla/valhalla

If you decide to use this project I can guide you through the process of setup.

**Comment by mrmrn** [comment]
thank you very much.
actually I made a mistake. we have a noisy location data from mobile devices. our problem is matching this data on the map because of their error values. for example our location data has an error range between 50-1000 meters. so we  dont know exactly where are they? but at first. we will  assume that these are GPS data and have no error. 
another point in my problem is we have a history of these devices location.
in this step the performance is not important for us. if we be able to matching this locations on map in any speed,it`s ok.

**Comment by categulario** [comment]
do you have sample data that I can see?

**Comment by mrmrn** [comment]
points can convert to location data. time stamp is the time that device is in that point. device is the device id. and accuracy is the accuracy of points location in meter.

**Comment by categulario** [comment]
how many locations do you have per device? Because this project assumes that you have many locations that conform a route or track for a device, then it finds the most likely route in the streets for this device

**Comment by mrmrn** [comment]
we have  3-5 locations per devices.
how much time do we need for example for 5 device and 5 locations?

**Comment by categulario** [comment]
This is what you can expect from this project:
https://gist.github.com/categulario/913aaf00a79207709dfbee6bb0c3df74

the gray line is the original location history for a device, and the colored lines are the result of applying the map-matching algorithm.

Part of the algorithm is also to find the closest streets from a single location.

**Comment by mrmrn** [comment]
> Part of the algorithm is also to find the closest streets from a single location.


this is what we exactly need in this step. because of we dont want track the people. we just want to know what street the user is in? and then sum up the user per street and have an aaproximation of traffic in streets.
So, could we have this closest street from your code with our data?

**Comment by categulario** [comment]
What you need is contained here: https://github.com/categulario/map_matching/blob/feature/phantom-nodes/lua/ways_from_gps.lua#L34-L44

as you can see that code is not in the `master` branch. I will try to publish that tomorrow so you can easily use it from the command line.

**Comment by categulario** [comment]
please note that your timezone is about 12 hours from mine, so `tomorrow` may not mean the same ;)

**Comment by mrmrn** [comment]
[this](https://github.com/categulario/map_matching/blob/feature/phantom-nodes/lua/ways_from_gps.lua#L34-L44) could be very useful to me. thank you very much. I am looking forward to it.

**Comment by categulario** [comment]
Well, I updated the master branch with the code needed to get the most plausible points on street for a GPS locations. This is the output:
https://gist.github.com/categulario/422f0d701d967320fa396749db0a454d

to run it you will need to follow the readme to setup the project, then run
```bash
$ ./main.py loadlua
$ ./main.py project -96.91364049911499 19.529918253277454
$ geojsonio build/projection.json
```
It assumes that you have the virtualenv activated and that you used `pip install -r requirements.txt` so you jave the `geojsonio` command. If not just open the `build/projection.json` file.

**Comment by mrmrn** [comment]
thank you very much. it works nice and great.
but for example with 

> -96.91364049911499 19.529918253277454


 it shows the probability of 4 segment around this point.
what we have in our database is a track of user on the map, so we will want to estimate the right segment for it.
we developed a code and its accuracy is well, but its performance  is terrible.

**Comment by categulario** [comment]
I'm curious about your code, is it somewhere I can see it?
Do you have multiple points that represent a single location?
I think I don't fully understand your case

**Comment by mrmrn** [comment]
I will explain our problem:
we have some devices,they report their locations every minutes. their location have a range of error between 50_100 meter. what we want at the end is the traffic in the streets. but when a device reports its location we dont know exactly where is it? we have a probability of street segments around it.
our solution is using `Dijkstra's algorithm`. 
our code is based on Dijkstra's algorithm and it works nice and accurate.but it takes a huge amount of time and resources and is written in PHP that is not for such works.
when I saw your code I thought it can helps us by inputing our devices location and returning the place and velocity of that device. if we know the devices speed and the street its moving across, the problem is solved.
thank you.

**Comment by categulario** [comment]
I see your problem. What I can provide is an accurate feasible route given the device's history of gps points. You can use multiple vehicle's routes to have an estimate of traffic. I'm in the process of improving speed by re-writing this project in a faster language. It will take probably a few weeks because I am the only programmer doing this. Unless someone helps me...

Soon I will have a service that can provide route estimates in real time, based on this code.

**Comment by mrmrn** [comment]
what we will use is a big matrices that include minimum distance between each two segments that are available in the area.
then with Dijkstra we will find the best match for that device in map.
we thing its accuracy is good and computational cost is fewer against another approaches.
but we will so happy to see your code.
good job.
thank you.
