### ISSUE TITLE
AttributeError: 'StrictRedis' object has no attribute 'geoadd'

### ISSUE THREAD

**Issue by mahboobehad** [categulario/map_matching#17]
I installed redis 3.2.9 also redis-py but i got following error:
 ```
map_matching git:(master) ✗ ./main.py loaddata       
Traceback (most recent call last):
  File "./main.py", line 322, in <module>
    val = locals()[args.task](*args.args)
  File "/home/mahboobe/develop/map_matching/lib/__init__.py", line 21, in wrapper
    return f(*args, **kwds)
  File "./main.py", line 31, in loaddata
    red.geoadd('base:nodehash', element['lon'], element['lat'], eid)
AttributeError: 'StrictRedis' object has no attribute 'geoadd'
```
what should i do?

thanks

**Comment by categulario** [comment]
You need redis-py from its master branch. GEO commands support hasn't been released to a version or tag. I recommend you to use virtualenv like this:

```bash
$ virtualenv env
$ source env/bin/activate
$ pip install -r requirements.txt
```

here I specify the redis-py version:
https://github.com/categulario/map_matching/blob/master/requirements.txt#L1

**Comment by mrmrn** [comment]
I had the same problem in ubuntu 16.04. I installed  map_matching in virtual env according to [this guide](https://www.unixmen.com/install-virtualenv-virtualenvwrapper-ubuntu/) and its runing very well .
thanks.
